/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as FarmsRouteImport } from './routes/farms'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as SampleRequestRouteImport } from './routes/sample-request'
import { Route as ForwarderTokenRouteImport } from './routes/forwarder.$token'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as TrackCodeRouteImport } from './routes/track.$code'
import { Route as ApiPublicDocumentsFileRouteImport } from './routes/api/public/documents/$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsRoute = FarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleRequestRoute = SampleRequestRouteImport.update({
  id: '/sample-request',
  path: '/sample-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ForwarderTokenRoute = ForwarderTokenRouteImport.update({
  id: '/forwarder/$token',
  path: '/forwarder/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCodeRoute = TrackCodeRouteImport.update({
  id: '/track/$code',
  path: '/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDocumentsFileRoute = ApiPublicDocumentsFileRouteImport.update({
  id: '/api/public/documents/$file',
  path: '/api/public/documents/$file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/farms': typeof FarmsRoute
  '/logistics': typeof LogisticsRoute
  '/rfq': typeof RfqRoute
  '/sample-request': typeof SampleRequestRoute
  '/forwarder/$token': typeof ForwarderTokenRoute
  '/track/$code': typeof TrackCodeRoute
  '/track/': typeof TrackIndexRoute
  '/api/public/documents/$file': typeof ApiPublicDocumentsFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/farms': typeof FarmsRoute
  '/logistics': typeof LogisticsRoute
  '/rfq': typeof RfqRoute
  '/sample-request': typeof SampleRequestRoute
  '/forwarder/$token': typeof ForwarderTokenRoute
  '/track/$code': typeof TrackCodeRoute
  '/track': typeof TrackIndexRoute
  '/api/public/documents/$file': typeof ApiPublicDocumentsFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof CatalogRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/farms': typeof FarmsRoute
  '/logistics': typeof LogisticsRoute
  '/rfq': typeof RfqRoute
  '/sample-request': typeof SampleRequestRoute
  '/forwarder/$token': typeof ForwarderTokenRoute
  '/track/$code': typeof TrackCodeRoute
  '/track/': typeof TrackIndexRoute
  '/api/public/documents/$file': typeof ApiPublicDocumentsFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/dashboard'
    | '/demo'
    | '/farms'
    | '/logistics'
    | '/rfq'
    | '/sample-request'
    | '/forwarder/$token'
    | '/track/$code'
    | '/track/'
    | '/api/public/documents/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/dashboard'
    | '/demo'
    | '/farms'
    | '/logistics'
    | '/rfq'
    | '/sample-request'
    | '/forwarder/$token'
    | '/track/$code'
    | '/track'
    | '/api/public/documents/$file'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/catalog'
    | '/dashboard'
    | '/demo'
    | '/farms'
    | '/logistics'
    | '/rfq'
    | '/sample-request'
    | '/forwarder/$token'
    | '/track/$code'
    | '/track/'
    | '/api/public/documents/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CatalogRoute: typeof CatalogRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  FarmsRoute: typeof FarmsRoute
  LogisticsRoute: typeof LogisticsRoute
  RfqRoute: typeof RfqRoute
  SampleRequestRoute: typeof SampleRequestRoute
  ForwarderTokenRoute: typeof ForwarderTokenRoute
  TrackCodeRoute: typeof TrackCodeRoute
  TrackIndexRoute: typeof TrackIndexRoute
  ApiPublicDocumentsFileRoute: typeof ApiPublicDocumentsFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms': {
      id: '/farms'
      path: '/farms'
      fullPath: '/farms'
      preLoaderRoute: typeof FarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample-request': {
      id: '/sample-request'
      path: '/sample-request'
      fullPath: '/sample-request'
      preLoaderRoute: typeof SampleRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forwarder/$token': {
      id: '/forwarder/$token'
      path: '/forwarder/$token'
      fullPath: '/forwarder/$token'
      preLoaderRoute: typeof ForwarderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$code': {
      id: '/track/$code'
      path: '/track/$code'
      fullPath: '/track/$code'
      preLoaderRoute: typeof TrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/documents/$file': {
      id: '/api/public/documents/$file'
      path: '/api/public/documents/$file'
      fullPath: '/api/public/documents/$file'
      preLoaderRoute: typeof ApiPublicDocumentsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CatalogRoute: CatalogRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  FarmsRoute: FarmsRoute,
  LogisticsRoute: LogisticsRoute,
  RfqRoute: RfqRoute,
  SampleRequestRoute: SampleRequestRoute,
  ForwarderTokenRoute: ForwarderTokenRoute,
  TrackCodeRoute: TrackCodeRoute,
  TrackIndexRoute: TrackIndexRoute,
  ApiPublicDocumentsFileRoute: ApiPublicDocumentsFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
